config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  resources :usuarios
  resources :comentarios
  resource :responder_comentarios

  root :to => 'home#index'
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :usuario
  has_many :responder_comentarios

  #validates :comentario, length: { maximum: 200 }
end

app/models/responder_comentario.rb
class ResponderComentario < ActiveRecord::Base
  belongs_to :comentario

  validates :respuesta_comentario, length: { maximum: 200 }
end

app/models/usuario.rb
#language: utf-8
class Usuario < ActiveRecord::Base
  has_many :comentarios
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Avatar
  has_attached_file :avatar,
                    :styles => { :medium => "300x300", :thumb => "100x100>" },
                    :default_url => 'missing.jpg'

  validates_attachment :avatar,
                       :size => { :in => 0..30.kilobytes },
                       :content_type => { :content_type => /\Aimage\/.*\Z/ }

  # Description
  #validates :description, length: { maximum: 200 }
  validates :name,
             length: { minimum: 3 }, # Lo deje en 5 por nombres como David, Laura, etc..
             presence: true,
             uniqueness: true

  validates :apellido,
             presence: true

  # Se anexa, aunque no es necesario, puesto que devise realiza dicha validación del email
  validates :email,
             format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ },
             uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end

end

app/controllers/comentarios_controller.rb
#language: utf-8
class ComentariosController < ApplicationController
  before_filter :authenticate_usuario!, only: [:index, :show, :new, :create, :update, :edit]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_comments

  def index
    @all_usuarios = Usuario.all
  end

  def new
    @comment = Comentario.new
  end

  def create
    @usuario = Usuario.find(current_usuario.id)
    @new_comment = @usuario.comentarios.new(secure_params)

    if @new_comment.valid?
      @new_comment.save
      flash[:notice] = "El comentario: #{@new_comment.comentario} se dio de alta..."
      redirect_to comentarios_path
    else
      render :new
    end
  end

  def show
    @show_comment = Comentario.find(params[:id])
    @usuario_comment = Usuario.where(id: @show_comment.usuario_id)
  end

  def edit
    @comment = Comentario.find(params[:id])
  end

  def update
    @update_comment = Comentario.find(params[:id])
    if @update_comment.valid?
      @update_comment.update(secure_params)
      flash[:notice] = "El comentario se actualizo correctamente..."
      redirect_to comentarios_path
    else
      flash[:notice] = "Error al actualizar el comentario #{@update_comment.comentario}"
      render :edit
    end
  end

  private
    def secure_params
      params.require(:comentario).permit(:comentario)
    end

    def invalid_comments
      redirect_to root_path, notice: '¡¡¡Problema con los comentarios!!!'
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/responder_comentarios_controller.rb
#language: utf-8
class ResponderComentariosController < ApplicationController
  before_filter :authenticate_usuario!, only: [:new, :create]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_responds

  def new
    @comentario_act = Comentario.where(id: params[:comentario_id])
    @respon_comentario = ResponderComentario.new
  end

  def create
    @comentario = Comentario.find(1)
    @new_respond = @comentario.responder_comentarios.new(secure_params)

    if @new_respond.valid?
      @new_respond.save
      flash[:notice] = "La respuesta se grabo correctamente..."
      redirect_to comentarios_path
    else
      render :new
    end

  end

  private
    def secure_params
      Rails.logger.debug "#{:comentario_id}"
      params.require(:responder_comentarios).permit(:respuesta_comentario)
    end

    def invalid_responds
      redirect_to comentarios_path, notice: '¡¡¡Se presento un problema al entrar a las respuestas!!!'
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_filter :authenticate_usuario!, only: [:index, :show]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_access

  def index
    @usuarios = Usuario.all
  end

  def show
    @show_user = Usuario.find(params[:id])
  end

  private
    def invalid_access
      redirect_to root_path, notice: 'Se tiene que registrar para poder ver la información...'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link(nombre, accion)
  end

  def buttons(nombre, ac, cl)
    button_to nombre, :action => ac, :class => cl
  end

  def buttons_back(nombre, ac, cl)
    button_to nombre, ac, class: cl
  end

end

app/helpers/comentarios_helper.rb
module ComentariosHelper

  # Opcion para mostrar comentarios:
  # 0 => Se mostraran solo 200 caracteres
  # 1 => Se mostrara todo el comentario
  # != de ( 0,1 ) => Se mostrara en blanco
  def mostrar_comentarios(comentario, opcion)

    html = ""
    unless comentario.nil?
      case opcion
      when 0
        # strip_tags => Clean all html
        html += strip_tags(comentario[0..200])

        Rails.logger.info(html)

        if html.length > 200
          html += "..."
        end
      when 1
        html = comentario
      else
        html = ''
      end

    end

    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/responder_comentarios_helper.rb
module ResponderComentariosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/comentarios/_form_comentarios.html.erb
<div class="row small-6 large-9 columns">
  <h3>Alta de comentarios:</h3>
  <div class="form large-11 columns">

    <%#= simple_form_for @comment do |form| %>
    <%#= form.input :comentario, autofocus: true, as: :text, :class => "ckeditor" %>
    <%#= form.button :submit, 'Submit', :id => "myButton" %>
    <%# end %>

    <%= form_for @comment do |f| %>
      <%= f.text_area :comentario, :col => 120, :row => 4, :class => "ckeditor" %>
      <%= f.submit 'Submit', class: "myButton" %>
    <% end %>

    <%= link_to t("form_text.back"), :back %>
  </div>
</div>

app/views/comentarios/edit.html.erb
<%= render 'comentarios/form_comentarios' %>

app/views/comentarios/edit.html.haml
= render 'comentarios/form_comentarios'

app/views/comentarios/index.html.erb
<h1>Comentarios de los usuarios:</h1>
<div class="row">

  <div class="large-9 columns">
    <% @all_usuarios.each do |usuario| %>
      <% usuario.comentarios.each do |cm| %>

        <div class="row">
          <div class="large-2 columns small-3">
            <%= image_tag(usuario.avatar) unless cm.comentario.empty? %>
          </div>

          <div class="large-10 columns">

            <p>
              <strong>
                <%= usuario.name %> dice:
                <br>
              </strong>

              <%= sanitize mostrar_comentarios(cm.comentario) %>
            </p>

            <ul class="inline-list">
              <li>
                <% if current_usuario.id == usuario.id %>
                  <%= link_to 'Editar', edit_comentario_path(cm.id) %>
                <% else %>
                  <%= link_to 'Contestar', new_responder_comentarios_path(comentario_id: cm.id) %>
                <% end %>
              </li>
              <li>
                <%= link_to 'Ver', controller: :comentarios, action: :show, id: cm.id %>
              </li>
            </ul>

          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/comentarios/index.html.haml
%h1 Comentarios de los usuarios:
.row
  .large-9.columns
    - @all_usuarios.each do |usuario|
      /- @all_comentarios = usuario.comentarios.page(params[:page]).per(5)
      - @all_comentarios = @all_usuarios.order("name").page(params[:page]).per(1)
      = paginate @all_comentarios
      /- @all_comentarios.each do |cm|
      - usuario.comentarios.each do |cm|
        .row
          .large-2.columns.small-3
            = image_tag(usuario.avatar) unless cm.comentario.empty?
          .large-10.columns
          %p
            %strong
              = usuario.name
              dice:
              %br
            = mostrar_comentarios(cm.comentario, 0)
            %ul.inline-list
              %li
                - if current_usuario.id == usuario.id
                  = link_to 'Editar',           |
                    edit_comentario_path(cm.id) |
                - else
                  = link_to 'Contestar',                                 |
                    new_responder_comentarios_path(comentario_id: cm.id) |
              %li
                = link_to 'Ver',            |
                  controller: :comentarios, |
                  action: :show,            |
                  id: cm.id                 |

app/views/comentarios/new.html.erb
<%= render 'comentarios/form_comentarios' %>

app/views/comentarios/new.html.haml
= render 'comentarios/form_comentarios'

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row small-6 large-9 columns">

  <div class="large-10 columns">

    <p>
      <strong>
        Comentario:
        <br>
        <% @usuario_comment.each do |usuario| %>
          Autor: <%= usuario.name %>
          <br>
        <% end %>
        <br>
      </strong>

      <%= sanitize @show_comment.comentario %>
      <hr>

      <p>
        <em><%= @show_comment.created_at.strftime("%d - %b - %Y [%H:%M]") %></em>
      </p>
    </p>

    <%= link_to t('form_text.back'), :back %>
    <%#= buttons_back(t('form_text.back'), "history.back()", "myButton") %>

  </div>

</div>

app/views/home/index.html.haml
.row.small-12.large-9.columns
  %h1
    = t("title.welcome")
    - if usuario_signed_in?
      = current_usuario.name
  %div
    %p
      = image_tag("indice_chat.jpeg", :class => "image_banner")

app/views/layouts/_footer.html.haml
.row
  %hr/
  .small-6.large-6.columns
    .inline-list.left
      = image_tag("bandera-usa.jpg", :class => "image_banderas")
      = link_to_unless_current "English", :locale => "en" |
      = image_tag("bandera-mexico.jpeg", :class => "image_banderas")
      = link_to_unless_current "Español", :locale => "es"
  .small-6.large-6.columns
    %ul.inline-list.right
      %li= link_to t("form_text.home"), root_path
      - unless usuario_signed_in?
        %li= link_to t("form_button.sign_in_button"), new_usuario_session_path
        %li= link_to t("form_button.sign_up_button"), new_usuario_registration_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'} round", "data-alert" => ""}
      = content_tag :div, sanitize(msg)
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
%nav.top-bar{"aria-hidden" => "true", "data-topbar" => "", "data-no-turbolink" => "", :role => "navigation", "data-options" => "sticky_on: large"}
  %ul.title-area
    %li.name
      %h1
        = link_to t("form_text.home"), root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    %ul.right
      = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li.divider
- if usuario_signed_in?
  %li.has-dropdown
    %a{:href => "#"}= image_tag current_usuario.avatar, :class => "image-decoration"
    %ul.dropdown
      %li= link_to t("form_button.edit_profile_button"), edit_usuario_registration_path
      %li.divider
      %li= link_to t("form_button.exit_account_button"), destroy_usuario_session_path, method: :delete
- else
  %li.divider
  %li= link_to t("form_button.sign_in_button"), new_usuario_session_path
  %li.divider
  %li= link_to t("form_button.sign_up_button"), new_usuario_registration_path

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Administrador"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main
      = render 'layouts/messages'
      -if usuario_signed_in?
        .row.small-12.large-3.columns
          %div
            .panel
              = image_tag("comentario.jpg")
              %h5
                = link_to "Usuarios", usuarios_path('index')
              %h5
                = link_to "Comentarios", comentarios_path('index')
              .section-container.vertical-nav{"data-options" => "deep_linking: false; one_up:true", "data-section" => ""}
                %section.section
                  %h5.title
                    = link_to "Nuevo comentario", new_comentario_path
      = yield
    %footer
      = render 'layouts/footer'

app/views/responder_comentarios/_form_respuesta_comentario.html.erb
<div class="row small-6 large-9 columns">
  <div class="form large-11 columns">

    <% @comentario_act.each do |cm| %>
      <h3>Respuesta al comentario " <%= cm.comentario.capitalize %> ":</h3>
      <%= hidden_field :comentario_id, :value => cm.id %>
    <% end %>

    <br>

    <%= simple_form_for @respon_comentario do |form| %>
      <%= form.input :respuesta_comentario, autofocus: true, as: :text, :maxlenght => 200 %>
      <%= form.button :submit, 'Submit', id: "myButton" %>
    <% end %>

    <%= link_to t("form_text.back"), :back %>
  </div>
</div>

app/views/responder_comentarios/new.html.erb
<%= render 'responder_comentarios/form_respuesta_comentario' %>

app/views/usuarios/index.html.haml
%h3 Usuarios del foro:
.row.large-9.columns
  - @usuarios.each do |users|
    .large-6.small-6.columns
      .large-12.columns.panel.callout.radius
        .large-5.columns.hovergallery
          = link_to(                     |
            image_tag(users.avatar,      |
            :class => "imagen-usuario"), |
            :controller => :usuarios,    |
            :action => :show,            |
            :id => users.id)             |
        .large-7.columns
        %strong
          = users.name
          = mostrar_comentarios(users.description, 0)
  .large-6.small-6.columns

app/views/usuarios/show.html.haml
%h3 Detalles del usuario:
.row.large-9.columns

  .large-11.columns.panel.callout.radius
    .large-3.columns
      = image_tag @show_user.avatar

    .large-9.columns
      %h3 Nombre:
      = @show_user.name

      %hr

      %h3 Apellido:
      = @show_user.apellido

      %hr

      %h3 Email:
      = @show_user.email

      %hr

      %h3 Descripcion:
      = mostrar_comentarios(@show_user.description, 1)

    = link_to 'Atras', :back